import './components/_header';
import './components/_nav';
import './components/_sliderProduct.js';
import './components/_sliderProducts.js';
import './components/_initFilters.js';
import './components/_init-fancybox3';
import './components/_init-validation-form';
import './components/_dropdown.js';
import './components/_ajax.js';
